language: node_js
node_js:
  - '10'
services:
  - postgresql
before_script:
  - psql -c 'CREATE DATABASE teamwork_test_db' -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - npm run coverage
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
env:
  global:
  - DB_USER=postgres
  - DB_NAME=teamwork_test_db
  - DB_PORT=5432
  - DB_PASSWORD=''
  - DB_HOST=localhost
  - CC_TEST_REPORTER_ID=b9dffe64ff9b1570eef3cc69cc4add47938822ca6127ef69e2d26e2f2ca55e1b
deploy:
  provider: heroku
  api_key:
    secure: CA1cfOFN/v7cCUlyuQ2vcnoGcCS03j2+XD9/Q0KLbnNNk0tbKsmaPZeFG45WaF6lanzxaTghFLzkGUFa6nMqeQ7SdYGl5ps5d3u23vNCTGRM2veM0LQZqrcTFcK7bB0c9W+DsmdBeWCBsVKtVShFCfOMg49GwtTRFrOrP9Sm4NhTnJwIuOJg+HFsKq/SS33CoEzFl6hftLVMyY2Gn3RmdBBxTTclOL2upGFPc1ZYNi+TPkb44hujctyZYFihf2I6T4v+7M1tkb4tGIXNex+CA5rcLWb73q7Ah+A353Nyau4CLT+9H+lBwnqVmbfun4Eky/KfBf68IqZOr9lbsEKZ7gJvc+Au5P96b8UjxdGmT7bu2xgQGfmadSaivfb00fkjA81HhGRdPUyD76bZ83o5fTd+2jzLmzU0M+ueNUs8x6RkrikxOFiktAcEtOy2PB02OhBN2YcOBsVc4N8gDknHyoymGhiBr9DqqixkDgAZ1zUgAN/+wPJumCcwihV6y49cMVGbqNGIlwQAmebc17DIE3aNwuyp4DlueuvGLDwixA8cde7skzyoRFaI9GEmLaEZeRJQYp0DB/gjA4zWNUUFw2lPPhsia8Panav4iNkfZAXIYAQg7YowBoYY4fd/8B1U+akUfAFLj6wCWksxd4uML1fsr0ufM9An/VuKNAv1uiY=
  app: devc-teamwork-rest-api
  on:
    repo: dave-ok/devc-teamwork-rest-api
    branch: develop
