language: node_js
node_js:
- stable
- '6'
- '4'
deploy:
  provider: heroku
  api_key:
    secure: rZC1XZ56/utG8p1J8FSOUPlQvo77QTQUpL+PS4Hahb79rbElPYQB+UPoH8mXcLMRoxAM1XLLyAtOrZaXGOKE1E7gsjXLvFSLuAVSS+8mzDbyjbuHlXP3IPWfW60CdwNBZnZ2ovTNeCAgEy6mroduc2IQVIeHs/S55FiNUsm/MpOKxpmPf8KYGJ3WoyitohXmB1teANDUw/YN7mqm0y1r+EC+lK/rGhneCLFZP4AJeFt9CA9Z3WE60IuDrNeZ7MLbLpGIWBkVMGL2FLQf+VM4DJBrk3JVEjnkL65iqFXbkEhkArtTx4r4Hw1AcDXQ++EU0I8O0k7/liA3uz5YZ8wS+skkWRkgyj6yJ7kiOnSkyR2n4V00ogCktmc45sqk9A431k7L3oqghJwfSL5mFBjEG8z6xnw5SIgqnuydAwNFjI7TVOx6kTAu1VTp37V/Vyc/SsgOEfpbV53p0VT/TETEiAp2YktFHTy0qk/QyqC9N53pCYA68sYPLrrrQeoFiaxxlLr28TkcNPnD8QiRTu61vOsH6KMoqDIS45iTh9A04PnFchpZ/U78DqbiZLKFnr6xb+LeI/3fzMDZyZKvudCZAxf+oZqSXaM8Uk+UtO77WAMwjfM2VJKa8ciagU6jK1YcHVAArS+0oJrGpOmpy3V9v5BDEY7LULn0UbltmM8ppt8=
  app: devc-teamwork-rest-api
  on:
    repo: dave-ok/devc-teamwork-rest-api
    branch: develop
